### ISSUE TITLE
Don't work on my setup.

### ISSUE THREAD

**Issue by mikhoul** [brian-girko/bookmarks-commander#1]
Hi,

I use Brave and BC don't see any bookmark at all ???

![image](https://user-images.githubusercontent.com/5678673/71855591-7a732d00-30af-11ea-94d5-b412c6d9b7b8.png)

![image](https://user-images.githubusercontent.com/5678673/71855629-92e34780-30af-11ea-800a-0a9ae0e04ff3.png)

Regards :octocat:

**Comment by brian-girko** [comment]
It works pretty well for me on Brave. What is your OS?
![aa](https://user-images.githubusercontent.com/51436935/71880881-27d65700-3129-11ea-90d1-af69c12f0124.png)

To debug, open the inspect window using the right-click context menu on the tab and see if you get any error on the "console" tab. btw, have you tried the extension on Google Chrome?

**Comment by mikhoul** [comment]
Here's the error in the console: 

![image](https://user-images.githubusercontent.com/5678673/71912988-80671d80-3144-11ea-9f3b-17dc67b40950.png)



Also it happen in Chromium with the same set of bookmarks so I think I have a clue of why it happen: In my  bookmarks Root folder I use a symbol `▷` so it coulb be the handling of such symbol that make the bug happen.

![image](https://user-images.githubusercontent.com/5678673/71913388-4d715980-3145-11ea-9718-d6a2719c1673.png)


N.b.: I'm under Win7

**Comment by brian-girko** [comment]
Thanks for the report. Sould have been fixed by 0.1.4 release.

**Comment by mikhoul** [comment]
I confirm the latest release fixed the issue. :+1: 

So now I see 2 annoying things that could be fixed easily mostly with CSS

1- Having **_2 independents scrollbars_** for each panes, it will be more easy to see/manage big folders with lot of bookmarks.

2- Having the tool bar at the bottom **_"fixed"_** (position) so even if I scroll I will have access to it.

Also a request being able to **_drag"n"drop_** from one pane to another would be greatly appreciated.

Best Regards :octocat:

**Comment by brian-girko** [comment]
Both issues are fixed by 0.1.5 release. Thanks for the report.

> drag"n"drop from one pane to another

For now, use Ctrl + right arrow key to move the selected items to the right pane and Ctrl + left arrow key for the reverse which places all the selected items after the selected element of the destination pane.
To change the order of a single directory, press Ctrl + M to mirror the active pane and do the arrangement like moving between two panes.
