### ISSUE TITLE
Bug: I can't scroll.

### ISSUE THREAD

**Issue by mikhoul** [brian-girko/bookmarks-commander#11]
I don't know if it is a regression but I wanted to clean /reorganize my bookmarks today and I can't scroll to see all my bookmarks.  
  
Even when I use the down arrow on my keyboard I can't see anything at the bottom of my screen.  
  
I use latest Brave version.  
  
Regards.

**Comment by brian-girko** [comment]
I see scrollbar on Brave; 
![a](https://user-images.githubusercontent.com/51436935/85250527-59787b80-b446-11ea-891f-af8da243c5be.png)

What is your OS?

**Comment by mikhoul** [comment]
Sorry I forgot to mention I use Windows 7 and brave 32 bit.  
  
Let me know if you need more information.  
  
Regards !   
  
 

![](https://user-images.githubusercontent.com/5678673/85307062-6a90af00-b47d-11ea-9af1-572577702a7c.png)

**Comment by brian-girko** [comment]
Still I am not able to reproduce even on Win7 (32bit). Have you tried on a clean profile?

<img width="764" alt="a" src="https://user-images.githubusercontent.com/51436935/85380914-ff9eb100-b52c-11ea-964f-754538bbea61.png">

**Comment by mikhoul** [comment]
Hummm,  
  
No since I use lot of extensions/userscripts.... but I will and will try to see what can interfere with the scrollbar and I will let you know,  
  
Regards !

**Comment by mikhoul** [comment]
I've made some testing on my side and it's really strange.  
  
I've tested with a portable version of Chrome et Iridium browser and both don't show scrollbar. 😵  
  
So something is wrong not with my browser but with my OS.....   
  
So it's not your extension that is the source of this problem.
