### ISSUE TITLE
duplicate finder

### ISSUE THREAD

**Issue by wuldfasche** [brian-girko/bookmarks-commander#12]
wondering if possible to add a duplicate finder

**Comment by brian-girko** [comment]
Can you elaborate? Do you mean the left and right panes displaying the same search result?

**Comment by wuldfasche** [comment]
Imagine you multiple duplicate bookmark entries, in unique folders and you didn’t know how what, how many or where they were - it would be useful to be able to locate them all in a list and multi- select and delete the undesired entries.

**Comment by brian-girko** [comment]
The search box now supports finding duplicated entries in the current root directory. Use the "duplicates" keyword in the search box to list all duplicated bookmarks. You can alternatively use Ctrl/Command + Shift + F.

**Comment by peter-kehl** [comment]
Hi Brian,

Thank you for Bookmarks Commander.

This "duplicate" keywords is a gem - but hidden. https://addons.mozilla.org/en-CA/firefox/addon/bookmarks-commander/ doesn't mention it. https://add0n.com/bookmarks-commander.html reads "Find Duplicated Bookmarks | Use Ctrl + Shift + F or Command + Shift + F" but it doesn't mention "duplicates" keyword.

Could you update both pages to help the users, please.
Thank you in advance on behalf of others.

**Comment by brian-girko** [comment]
@peter-kehl done!

**Comment by peter-kehl** [comment]
Thank you for updating add0n.com.

However, https://addons.mozilla.org/en-CA/firefox/addon/bookmarks-commander/ still reads `[find duplicated bookmarks]: Ctrl/Command + Shift + F` but it doesn't mention `duplicates` keyword.

**Comment by brian-girko** [comment]
@peter-kehl just added it to AMO as well.
