### ISSUE TITLE
Add option resizable colum

### ISSUE THREAD

**Issue by StillDan** [brian-girko/bookmarks-commander#13]
Is it possible add resizable column name, path, link?

**Comment by brian-girko** [comment]
As of the next release, there are two methods to resize. For temporary resize, drag the new column resizer. For persistent resize, use the new `columns-width=` on Ctrl + S or Command + S prompt box.

**Comment by StillDan** [comment]
> 
> 
> As of the next release, there are two methods to resize. For temporary resize, drag the new column resizer. For persistent resize, use the new `columns-width=` on Ctrl + S or Command + S prompt box.

Ou!!! Thank you so match! It's best of BM manager now!!!!

**Comment by StillDan** [comment]
Not quite clear about persistent resize. Can I see an example? Couldn't figure out the syntax, what where

**Comment by brian-girko** [comment]
This is the one that currently works `column-widths=100, 32, 32`, but it should work with `column-widths=100px, 32px, 32px`. Will fix this by the next release.

**Comment by StillDan** [comment]
Thank you very much. Now I see.
 


С уважением,

Данила Туманов

-- 

mob: +79645856066
         +14155494920

skype: still__



 

----- Reply to message -----
Subject: Re: [brian-girko/bookmarks-commander] Add option resizable colum (#13)
Date: ср, 2 дек. 2020, 08:20
