### ISSUE TITLE
Find Duplicates in a folder

### ISSUE THREAD

**Issue by QuantillionMe** [brian-girko/bookmarks-commander#14]
When I do Ctrl+Shift+F from within a folder, the directory goes to _Duplicates for "Root________"_ with what seems to be ALL the (11k+) duplicates in my directory. How do I _selectively_ search for _only_ the duplicates in the folder I'm currently in? 

(Also, FAQ 6: "Now on one pane place the active item to the location where you need the selected items to get moved next to this item." - I don't understand this.) 

Like all ThunderBird plugins, this needs a Community forum.

**Comment by brian-girko** [comment]
When you are on a directory, the extension is supposed to search the current directory. The bug is now fixed. Thanks for the report.
