### ISSUE TITLE
Support different APIs like http://pinboard.in

### ISSUE THREAD

**Issue by rafi** [brian-girko/bookmarks-commander#16]
Great extension! Unfortunately for me, I keep all my bookmarks at http://pinboard.in/

Would be wonderful to be able to use it with my Pinboard bookmarks :)

**Comment by brian-girko** [comment]
This extension is very dependent on the browser bookmark's APIs. So Supporting a new async service is pretty hard and increases the complexity of the code. Instead, I would recommend finding an extension that syncs the changes in the bookmark tree to the external service.
