### ISSUE TITLE
Open Link in New Tab + a few other (Feature Requests) 

### ISSUE THREAD

**Issue by washere** [brian-girko/bookmarks-commander#19]
Thanks for this, it is superb, honestly beyond words for NC veterans and anyone new.

1) Can we have a Right_Click option to:
OPEN LINK IN NEW TAB

This is simply indispensable for working with large number of bookmarks, which is reason for this great work.
For many many reasons and scenarios.

Also Would be great to have:

2) CTRL + Click would also open in link in new tab
This would be great for pro coders who are keyboard focused.

3) Open Link in New Window
This would be good too, secondary to open in new tab in terms of usefulness.
This can be ALT + Click, or SHIFT or combo of any two CTRL/ALT/SHIFT plus click on link.

I think if you tried yourself you would love it yourself for:
Numerous Bookmark Daily Functions
+
Complex Bookmarks Management & Manipulation

Thanks again for this amazing work, it simply is the best.

**Comment by washere** [comment]
Few other ideas, as I do not want to open new threads:

4) MOVE:
Move a bookmark or folder:
UP
DOWN

Within bookmarks, not sub-folders, so only works at root, makes it easier for you.
If can move up a level within subfolders would be even better.


5) PROPERTIES:
Shows a bookmarks location, if  in root or subfolders etc.
Very useful in search results.

I think you'd love these yourself as they give so much power to your engine code which is the hard work you have already done.
Thanks again.

**Comment by washere** [comment]
Plus: Any of the above 5 suggestions can be implemented in any way you like:

i) Right_Click
ii) Buttons at bottom Toolbar
iii) Both of above or any way you see fit

Thanks again.

**Comment by washere** [comment]
I just edited the title to reflect it includes a few other feature requests.

Another feature I think we would all like to use came to my mind:

6) Copy / Cut / Paste Bookmark (as a whole)
So we can copy & paste a whole bookmark (URL + Title) to somewhere else.
Or move (cut & paste) a whole bookmark.

This would be very useful in large bookmark collections, which is the target audience of this great work.
Instead of tediously going up/down the list slowly.
And only copying parts (URL then Title) of the bookmark and pasting them in two further processes, that is a 4 step process just to copy/cut & paste a bookmark somewhere else. Even longer in large bookmark collection cases.

Thanks again.

**Comment by brian-girko** [comment]
> Can we have a Right_Click option to:

Done! Alternatively, you can use Ctrl + Enter
> CTRL + Click would also open in link in new tab

In this extension Ctrl + Click and Shift + Click are used to append to selection. Use Ctrl + Double-click or Ctrl + Enter

> Move a bookmark or folder:

If you don't like the current mirror method, after the next release, you can drag and drop between panes.

> Shows a bookmarks location, if in root or subfolders etc.

The top path-view displays the current location. For search results, we do have a column for the path.

**Comment by washere** [comment]
OMG Brian, you are an angel. Thank you very much.
And you have done them all in the best ways possible. 

Might be good to add delete to right_mouse_click too (keeping the toolbar delete too). Many are used to that in stock manager, easy peasy for a genius coder. Actually the stock bookmark manager is now just a subset of yours, no need for it anymore.

I forgot the path columns in search results, actually used that before last year but slipped my mind.
Any chance of enabling the standard sort by clicking on columns titles, and reverse sort per usual?
That would be cool. Of course if your libkit does not support it, that is OK. But would be very useful in search results.
The top path row i totally missed, due to my ignorance, hidden in plain sight, never noticed it. Thanks for telling me that too.

In your Github homepage: Might be good to do a simple 2 column explanations list of:
buttons/clicks combos + description
So as you add features, even old users see the new features.

And also add 2 links to the extension pages for Chrome and Firefox. Many are not coders like us nor techie and can just play and learn. Otherwise they might land on your Github and then not find the actual extensions.

I can open a new thread if i get any new requests for you.

I can't thank you enough. Great jobs like your work  take time to go viral (long tail) but sooner or later they will catch on in a big way.

Thanks again buddy, you are a star. ⭐ 👍
