### ISSUE TITLE
Tool bar button barely visible

### ISSUE THREAD

**Issue by smaragdus** [brian-girko/bookmarks-commander#2]
First I would like to thank the developer for this very useful cross-browser extension.

I have noticed that when a darker theme is used (for example- [Oceanic](https://chrome.google.com/webstore/detail/oceanic/gbbacdmgjdfajabgglpjifcedoajdimg)), the tool bar button is hardly visible, screen:

![Bookmarks Commander 0 1 8 - 2020-03-27 - 006](https://user-images.githubusercontent.com/9025757/77784226-df14a700-7062-11ea-852f-48814109136a.png)

as the icon colour is quite similar to the theme colour.

So I would like to suggest an option for alternative tool bar icon (for example- yellow) which will improve the tool bar button visibility on darker themes.

**Comment by brian-girko** [comment]
Thanks for the report. As of the next release, you can use Ctrl/Command + S and then `icon=light` or `icon=dark` to change the icon.

**Comment by smaragdus** [comment]
@brian-girko 

Thanks for the implementation and for the tip.

I forgot to mention that on Firefox with dark theme (in my case- [Dark Gold)](https://addons.mozilla.org/en-US/firefox/addon/dark-gold/), screen:

![Bookmarks Commander 0 1 8 - 2020-03-29 - 003](https://user-images.githubusercontent.com/9025757/77839992-fbabfe80-718a-11ea-9edc-dd0bebfb2efa.png)

the button looks better.

I will wait for the new release.

Regards
