### ISSUE TITLE
Suggestion: useful command: `Select current Dir on the other pane`

### ISSUE THREAD

**Issue by schittli** [brian-girko/bookmarks-commander#20]
#### Thanks a lot for your great work and for sharing it!, 
it's unbelievable that Google does not offer it out of the box.

#### I have a small suggestion:
while working with two panes, it is very useful to make the other pane navigate to the currently selected item. For example:

1. The left pane has selected this Dir: `/bookmarks/Study/Mathematics/Dynamical systems/differential equations`
2. Now, the User presses a hotkey
3. Then, the other pane (the right pane) automatically navigates into the selected Dir of the left pane (`/bookmarks/…/…/…/differential equations`)

For example, this is useful when cleaning up the directory structure and the source and destination are very close to each other.

The workflow looks like this:

1. Select the Source:
![image](https://user-images.githubusercontent.com/8282673/122673997-8d11f100-d1d3-11eb-8d60-7d08f6ce6de1.png)
2. Change to the other pane and select the Dir:
![image](https://user-images.githubusercontent.com/8282673/122674200-54264c00-d1d4-11eb-9474-826cada5ce4e.png)

As an example, in Total Commander this action can be called by those hotkeys:
```
Ctrl right » the selected item in the left pane is selected in the right pane. 
             If a Dir is selected, then the right pane jumps into this Dir
Ctrl left » the selected item in the right pane is selected in the left pane. 
             If a Dir is selected, then the left pane jumps into this Dir
```

Thanks a lot, kind regards,
Thomas

**Comment by brian-girko** [comment]
Changes on 0.2.7 release

Ctrl + M -> Mirrors the inactive pane and selects the same items
Ctrl + Shift + M > Navigates the inactive pane to the first selected dir
