### ISSUE TITLE
How to change the default hot key?

### ISSUE THREAD

**Issue by sd309991** [brian-girko/bookmarks-commander#21]
How to change the default hot key?

Changing title of a bookmark in Windows use Ctrl+ T, while it will open a new tab in Edge. Is it possible to change it to F2?

Thank you!

**Comment by brian-girko** [comment]
It is still not possible to configure shortcuts. Though for changing the bookmark's title this extension uses Ctrl + E. Does it conflict with anything?

**Comment by sd309991** [comment]
> It is still not possible to configure shortcuts. Though for changing the bookmark's title this extension uses Ctrl + E. Does it conflict with anything?

Thank you, Brian! You have save my hours this after. And I also want to know the shortcut to select the top bookmark item of the active panel? I knew I could use backspace and enter, but it would be great that I can just press a shortcut key and go up like in window explorer we can use ctrl + home.

Yours
Sam

**Comment by brian-girko** [comment]
0.2.7 will supports Home and End keys.
