### ISSUE TITLE
add a function for import and export a single folder from (to) an html file 

### ISSUE THREAD

**Issue by test-0-zero** [brian-girko/bookmarks-commander#24]
I think is a good idea to have a function that can import (and export) a single folder from (to) an html (or json) file, into another folder or where I want.

Export to a json file already exist, but its impossible to import from a json file to an specific folder.

thanks a lot.

**Comment by brian-girko** [comment]
> but its impossible to import from a json file to an specific folder.

Ctrl/Command + P?

https://add0n.com/bookmarks-commander.html#faq4

**Comment by test-0-zero** [comment]
You are right!
I didn't understand the double pass (faq 9)  and was thinking of a key combination that would open a file selector for import.

Thanks so much.
