### ISSUE TITLE
Open PATH Folder in This Pane or Opposite Pane + Back/Forward

### ISSUE THREAD

**Issue by washere** [brian-girko/bookmarks-commander#25]
Thanks again for the best bookmark extension.

Regular Scenario:
You bookmark a site
Want to put it in relevant subfolder or subfolderS
Search (CTRL+F) for some similar bookmarked sites
We get a list of result hits:
The PATH column in results shows a relevant subfolder OR SEVERAL relevant subfolders
We choose which subfolder (in path column) we want the new site to be bookmarked in
We have bookmarked the new site at bottom of root of Bookmarks (BOOKMARS BAR), so we find it fast
The root of bookmarks can be the other pane, opposite the search results pane

NOW WE NEED:
Right_click on any result (we see the PATH column) of the search hits, we have 2 new options:

Open Path Folder
Open Path Folder in Opposite Pane 

Now we can simply move or copy the new bookmark to the desired Path Subfolder or subfolderS

if only one can be done, then:
Open Path Folder in Opposite Pane
is much more useful to copy/move to multi folders.
But both are really essential.

This feature should be fairly easy to code for a master like Brian, but really opens up much usefulness and potential horizons.

It would be nice to have BACK/FORWARD for the history.
Current right_mouse click is the standard chrome which doesn't work.
The Back/Forward ca n be done by:
2 buttons in bottom toolbar +
The 2 back/forward buttons on numerous Mouse models (Wired, Wireless dongle, Bluetooth)
This feature can be tricky to code and is a minor request, but it will mega useful for pro users too.

Thanks again for this gift of an extension.

**Comment by brian-girko** [comment]
The new release has these two context menu items. Alternatively, the user can press Alt + M to perform "Open Path Folder in Opposite Pane".

> It would be nice to have BACK/FORWARD for the history

I added the support. However, I am not still sure if it always works. You can now use the browser's "Back" and "Forward" buttons to navigate visited views. Also, you can use the "History" menu to fast forward/backward between views.

**Comment by washere** [comment]
That or rather those are just marvelous.

The mouse back and forth is working well too. Just needs to work often. Ever Growing numbers who have bought a mouse with these 2 side buttons, never can go back. And more and more software are incorporating them in the UI/UX navigation.

This plugin (extension) is slowly growing into an unrivaled beast. It will be good freebie PR vehicle for any venture you might starting future, bringing many to you. Might start with a blog about your plugins on Github.

Thanks again buddy.
