### ISSUE TITLE
Update Firefox version

### ISSUE THREAD

**Issue by peter-kehl** [brian-girko/bookmarks-commander#32]
Hi Brian,

1. https://addons.mozilla.org/en-CA/firefox/addon/bookmarks-commander/versions shows v. 0.2.8 from Aug 17, 2021. But GIT shows newer fixes since then. Could you upload the newest version to Mozilla Addons, please?

2. Could it be possible to update the Mozilla Addons version number to reflect GIT 0.4.4?

**Comment by brian-girko** [comment]
The extension recently moved to manifest v3. This is not yet supported in FF. I'll try to manually modify incompatible scripts and update the FF version by the next release.
