### ISSUE TITLE
"duplicates" -> Delete

### ISSUE THREAD

**Issue by peter-kehl** [brian-girko/bookmarks-commander#33]
When a search for "duplicates" returns one (or more) duplicates, and the user right clicks at any of those occurrences and chooses "Delete" from the context menu, currently it removes both matches/occurrences. (Unsure if it removes all results for "duplicates" if there are more than two, but either way...).

Please make it remove only the occurrence that was right-clicked on. Or create a better workflow. Or, if there is an existing better workflow, make it more intuitive/obvious.

**Comment by brian-girko** [comment]
I am not able to reproduce this on Chrome. When I select a single bookmark in the duplicate pane, it only removes the selected bookmark. What is your browser? Do you have the same issue with Ctrl + Delete?

**Comment by peter-kehl** [comment]
Sorry, confirming that it does work: It deletes only one of the two duplicates.

What scared me was that after the delete, I intuitively expected the other match to still show up. Of course, that's contrary to the "duplicates" filter (since there may be other pairs/sets of duplicates).

(I'm on Firefox.)
Thank you.
