### ISSUE TITLE
[Feature Request] Drop inside folder dragging items over its icon

### ISSUE THREAD

**Issue by dylan666** [brian-girko/bookmarks-commander#35]
It would be possible to add an option for dragging items "inside" folders icon and not below?
I read the FAQ #5 but moving bookmarks without opening each folder would be so much faster...

Thank you

**Comment by brian-girko** [comment]
Thanks for the request. As of the next release, there is a visual indicator of the place where the drop happens. Also, you can use the Shift key over a directory to drop inside it.

**Comment by dylan666** [comment]
I saw that the version here is 4.8 updated 3 months ago, but on Firefox portal we still have 0.4.6 update 6 months ago.
Will this versions uploaded on that portal for automatic update? Or should I update it from file?
Thank you for your time
