### ISSUE TITLE
further sorting options

### ISSUE THREAD

**Issue by tofostay** [brian-girko/bookmarks-commander#4]
program would greatly benefit from further sorting criteria: name, date added, date modified, plus ascending/descending. This should be achievable by clicking on the respective column header in the pane.

**Comment by dembeck** [comment]
I would like the option to sort by site, then by page title. I have a lot of folders that have several links for different pages on the same site.

**Comment by brian-girko** [comment]
we are going to have custom sorting (Alt + J and Alt + Shift + J). So you can enter something like `link, name` to sort based on URLs, then sort based on names.
