### ISSUE TITLE
keyboard shortcut to deselect

### ISSUE THREAD

**Issue by tofostay** [brian-girko/bookmarks-commander#6]
shift+(up/dn), ctrl+(up/dn) and shift+ctrl+(up/dn) all have the same effect, adding the next item above/below current selection. 

It would be useful to have one keyboard shortcut for adding to selection, and another for taking away from selection. 

eg: shift+(up/dn) to add, 
ctrl+shift+(up/dn) to take away.

And it would be good to have same with page-up and page-dn.

**Comment by brian-girko** [comment]
on 0.1.9 release, shift + ctrl + up/down is the reverse of ctrl + up/down
