### ISSUE TITLE
behaviour when returning from search result to full list

### ISSUE THREAD

**Issue by tofostay** [brian-girko/bookmarks-commander#8]
having done a search, we get a search result ('filtered' list), but there doesn't seem to be an intuitive way to come back to the full list. Clicking on the search term (above the pane), I get message 'bookmark id is invalid' (Chrome & Edge) ('root is null' in FF) and then jump back to root level. 

Better would be to have a [...] as the top item above the filtered list and clicking this we come back to the folder we were in before we started the search. Esc key should have same functionality. 

Also to note that search is always a global search over all bookmarks and not limited to the bookmarks of the folder from within which you start the search.

**Comment by brian-girko** [comment]
we are going to have a new "[..]" on top of the search results. Same as normal "[..]" you can use "Backspace" as a shortcut.
