### ISSUE TITLE
BUG? 'Esc' from search dialog

### ISSUE THREAD

**Issue by tofostay** [brian-girko/bookmarks-commander#9]
possible BUG? find function (window mode & tab mode only) (Chrome & Edge only, not FF): 

ctrl-F to open the search dialog, but then cancel it **by pressing esc**. 

Results in neither pane having 'focus', and cannot gain focus, not by clicking in a pane nor by pressing Tab. 

Can 'repair' by switching to another tab/window and back again.

**Comment by brian-girko** [comment]
This is a browser bug that does not generate a "focus" event after the dialog is dismissed, so I ditched the "window.prompt" in favor of our new custom element prompt. Should have fixed this bug.
